eureka:
  client:
    register-with-eureka: false
server:
  port: 8222
spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: category-service
          uri: http://localhost:8070
          predicates:
            - Path=/api/v1/category/**
        - id: product-service
          uri: http://localhost:8071
          predicates:
            - Path=/api/v1/product/**

management:
  endpoints:
    web:
      exposure:
        include: refresh
  tracing:
    sampling:
      probability: 1.0