server:
  port: 8888

spring:
  profiles:
    active: native, vault
  cloud:
    config:
      server:
        vault:
          kv-version: 2
          host: 127.0.0.1
          token: hvs.UVNZwylNHopxicKTfK8SUUzZ
        native:
          search-locations: classpath:/configuration

